model:
  input_channels: 1
  conv1_out_channels: 32
  conv2_out_channels: 64
  fc1_out_features: 128
  fc2_out_features: 10
  dropout: 0.5

training:
  weight_decay: 0.0001
  batch_size: 64
  epochs: 5
  learning_rate: 0.001
  seed: 42

dataset:
  name: "FashionMNIST"
  root: "./data/image_classification/fashion_mnist"
  normalize_mean: 0.1307
  normalize_std: 0.3081

# 新增日志配置
logging:
  level: "INFO" # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "Experiment_Log/image_classification/CNN/cnn_fashionmnist_run.log" # 日志文件保存路径
