model:
  input_channels: 1
  conv1_out_channels: 32
  conv2_out_channels: 64
  fc1_out_features: 128
  fc2_out_features: 10
  dropout: 0.5

training:
  batch_size: 64
  epochs: 5
  learning_rate: 0.001
  seed: 42

dataset:
  root: "./data"
  normalize_mean: 0.1307
  normalize_std: 0.3081