dataset:
  name: "cifar10"
  root: "./data/image_classification_data"
  image_size: [224, 224]
  normalize_mean: 0.1307
  normalize_std: 0.3081
  validation_split_ratio: 0.2 # <-- 新增：将20%的训练数据作为验证集
  data_augmentation: true # <-- 新增：为训练集启用数据增强

training:
  weight_decay: 0.0001
  batch_size: 64
  epochs: 5
  learning_rate: 0.001
  seed: 42

# 新增日志配置
logging:
  level: "INFO" # 日志级别: DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "Experiment_Log/temp.log" # 日志文件保存路径
